name: tokopedia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  carousel_slider: ^4.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  intl_phone_number_input: ^0.7.2
  step_progress_indicator: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/menu/
    - assets/banner/
    - assets/logo/
    - assets/diskonan/
    - assets/promo/
    - assets/produk/
    - assets/dll/
