name: tokopedia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.2
  file_picker: ^5.2.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.2
  flutter_facebook_auth: ^5.0.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  google_sign_in: ^5.4.4
  intl_phone_number_input: ^0.7.2
  pinput: ^2.2.31
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/menu/
    - assets/banner/
    - assets/logo/
    - assets/diskonan/
    - assets/promo/
    - assets/produk/
    - assets/detail/
    - assets/dll/
